default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  adapter: postgresql
  database: bank_manager_dev
  pool: 5
  timeout: 5000
test:
  <<: *default
  adapter: postgresql
  database: bank_manager_test
  pool: 5
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  database: bank_manager_production
  username: bank_manager
  password: <%= ENV['BANK_MANAGER_DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000